DROP DATABASE IF EXISTS playstore;
CREATE DATABASE playstore;
use playstore;

create table reviews(
Translated_Review longtext,
App varchar(100),
Sentiment varchar(100),
Sentiment_Polarity varchar(100),
Sentiment_Subjectivity varchar(100));

create table apps(
app longtext,
category varchar(255),
rating varchar(255),
reviews int,
size varchar(255),
installs int,
type1 enum ('Free' , 'Paid'),
price int,
content_rating varchar(100),
genres varchar(255),
last_update date,
current_version varchar(100),
android_version varchar(255));

# 1 Highest rating apps
select App from apps
where Rating = 5;

# 2 Number of installs and reviews for the highest rated apps in descinding order of reviews

select App, sum(Reviews) as no_of_reviews, sum(Installs) as no_of_installs
from apps
where Rating = 5
group by App
order by Reviews desc;

# 3 Highest number of reviews? mention the number of reviews and category

select App, sum(Reviews) no_of_reviews, Category
from apps
group by App 
order by Reviews desc
limit 1;

# 4 Total amount of revenue generated by the google play store by hosting apps?

select sum(Price*Installs) as total_revenue
from apps;

# 5 Category of apps with the highest number of installs? 

select category,sum(installs) as total_ins
from apps
group by category
order by total_ins
limit 1;
	
# 6 Genre with the most number of published apps

select genres, count(genres)
from apps
group by genres
order by genres
limit 1;

# 7 Provide the list of all games ordered in such a way that the game
# that has the highest number of installs is displayed on the top

select distinct app
from apps
where Category = 'GAME'
order by Installs;

# 8 Provide the list of apps that can work on android version 4.0.3 and UP

select app
from apps
where Android_Version ='4.0.3 and up';

# 9 Number of free apps and number of paid apps

select Type1 ,count(Type1)
from apps
group by Type1;

# 10 The best dating app? (Best dating app is the one having the highest number of Reviews)

select app
from apps
where Reviews = (select max(Reviews) from apps where Category = 'DATING') and Category = 'DATING';

# 11 Number of reviews having positive sentiment and number of reviews having negative sentiment for the app "10 best foods for you" and compare them.

select Sentiment,count(Sentiment)
from reviews
where App='10 Best Foods for You'
group by Sentiment;

# 12 Comments of "ASUS SuperNote" having sentiment polarity and sentiment subjectivity both as 1

select Translated_Review
from reviews 
where App='ASUS SuperNote' and Sentiment_Polarity =1 and Sentiment_Subjectivity =1;

# 13 Get all the neutral sentiment reviews for the app "Abs Training-Burn belly fat"

select Translated_Review
from reviews
where App='Abs Training-Burn belly fat' and Sentiment= 'Neutral';

# 14 Extract all negative sentiment reviews for "Adobe Acrobat Reader" with their sentiment polarity and sentiment subjectivity

select Translated_Review , Sentiment_Polarity, Sentiment_Subjectivity
from reviews
where App='Adobe Acrobat Reader' and Sentiment= 'Negative';

